### ISSUE TITLE
ReadMe: citation preferences?

### ISSUE THREAD

**Issue by augustfly** [JeffLCoughlin/EphemMatch#1]
hi, i'm one of the data editors for the ApJ/AJ: the readme to this repo has a preferred citations block (great!) but that block refers to Model-Shift rather than EphemMatch. Are the citations themselves correct for EphemMatch? Trying to get it right in an accepted paper.

**Comment by JeffLCoughlin** [comment]
Hi - Thank you, good catch! I have updated the README. The use of "Model-Shift" was a typo I didn't catch when copy+pasting and updating from another repository - I have updated it to "EphemMatch". The two citations listed are correct for EphemMatch.  Thank you so much!
